---
apiVersion: v1
kind: Service
metadata:
  name: {{ template "icn-kms-node.nginx.name" . }}
  labels:
    app: {{ template "icn-kms-node.name" . }}
    chart: {{ template "icn-kms-node.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  ports:
    - protocol: TCP
      port: 443
  selector:
    app: {{ template "icn-kms-node.application.name" . }}
    release: {{ .Release.Name }}
